version: '3.9'

networks:
  libSystem:

volumes:
  database-volume:

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Tusha23!
      MYSQL_DATABASE: LibSystem
      MYSQL_USER: NIKITA
      MYSQL_PASSWORD: Nikita11!
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - libSystem
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3306:3306"

  backend:
    image: nikki00011/libmntsys-backend
    environment:
      DB_URL: jdbc:mysql://database:3306/LibSystem?createDatabaseIfNotExist=true
      DB_USERNAME: NIKITA
      DB_PASSWORD: Nikita11!
    networks:
      - libSystem
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: nikki00011/libmntsys-frontend
    networks:
      - libSystem
    ports:
      - "5173:5173"
    depends_on:
      - backend

